stages:
  - maven-package
  - kaniko-build
  - kaniko-web-build

variables:
  MAVEN_CLI_OPTS: "--no-transfer-progress"
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -DproxySet=true -Dhttp.proxyHost=chckproxy.raiffeisenbank.com.ua -Dhttp.proxyPort=8080 -Dhttps.proxyHost=chckproxy.raiffeisenbank.com.ua -Dhttps.proxyPort=8080 -DnonProxyHosts=$NO_PROXY"

maven-package:
  stage: maven-package
  image: nexus.otpbank.com.ua:10443/repository/tools/maven-3.8.5-openjdk-17-slim
  before_script:
    - echo -n "$SSL_CHAIN" | base64 -d > /usr/local/share/ca-certificates/cert.crt && update-ca-certificates
    - keytool -importcert -file /usr/local/share/ca-certificates/cert.crt -alias ca_certs -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit -noprompt
    - 'echo "cafile: \"/usr/local/share/ca-certificates/cert.crt\"" > ~/.yarnrc'
  script:
    - echo "PARENT_VERSION=$(mvn --non-recursive help:evaluate -Dexpression=project.version | grep -v '\[.*' | tail -1 | cut -d'-' -f1)" >> parent.env
    - mvn install $MAVEN_CLI_OPTS -e -DskipTests
  cache:
    paths:
      - .m2/repository
    key: $CI_BUILD_REF_NAME
  artifacts:
    reports:
      dotenv: parent.env
    paths:
      - api-gateway/target/*.jar
      - api-server/target/*.jar
      - scheduler/target/*.jar
      - cpms/target/*.jar
      - downloader/target/*.jar
      - importer/target/*.jar
      - enricher/target/*.jar
      - migrations/target/*.jar
      - sandbox/target/*.jar
      - uploader/target/*.jar

.kaniko-build: &kaniko-build
  stage: kaniko-build
  image:
    name: nexus.otpbank.com.ua:10443/repository/tools/ca-2047/kaniko-project/executor:v1.22.0
    entrypoint: [""]
  needs:
    - maven-package
  before_script:
    - echo "{\"auths\":{\"$ANTIFRAUD_NEXUS_IMAGE_REPO\":{\"auth\":\"$(printf "%s:%s" "$ANTIFRAUD_NEXUS_USER" "$ANTIFRAUD_NEXUS_PASS" | base64 | tr -d '\n')\"}, \"$NEXUS_IMAGE_REPO_FROM\":{\"auth\":\"$(printf "%s:%s" "$NEXUS_USER" "$NEXUS_PASS" | base64 | tr -d '\n')\"}}}" >> /kaniko/.docker/config.json
    - echo "{\"proxies\":{\"default\":{\"httpProxy\":\"$HTTP_PROXY\",\"httpsProxy\":\"$HTTP_PROXY\",\"noProxy\":\"$NO_PROXY\"}}}"  >> /kaniko/.docker/config.json

services-build:
  <<: *kaniko-build
  script:
    - >-
      for file in $(find . -type f -regex '.*target/.*\.jar'); do
        echo "Processing file: $file"
        base_name=$(basename "$file" .jar)
        echo "Base name: $base_name"
        app_name=$(echo "$base_name" | sed -E 's/-[0-9]+\.[0-9]+\.[0-9]+.*//; t; s/.*/ /')
        if [ -z "$app_name" ] || [ "$app_name" = " " ]; then
          echo "Failed to parse app_name from $base_name"
          exit 1
        fi
        echo "App name: $app_name"
        echo "Version: $PARENT_VERSION"
        /kaniko/executor \
          --context . \
          --dockerfile $CI_PROJECT_DIR/Dockerfile \
          --destination "$ANTIFRAUD_NEXUS_IMAGE_REPO/$app_name:$PARENT_VERSION" \
          --build-arg JAR_FILE=$file \
          --build-arg http_proxy=$HTTP_PROXY \
          --build-arg https_proxy=$HTTP_PROXY || continue
        echo "Image $app_name:$PARENT_VERSION pushed!"
      done

kaniko-web-build:
  stage: kaniko-web-build
  image:
    name: nexus.otpbank.com.ua:10443/repository/tools/ca-2047/kaniko-project/executor:v1.22.0
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"$ANTIFRAUD_NEXUS_IMAGE_REPO\":{\"auth\":\"$(printf "%s:%s" "$ANTIFRAUD_NEXUS_USER" "$ANTIFRAUD_NEXUS_PASS" | base64 | tr -d '\n')\"}, \"$NEXUS_IMAGE_REPO_FROM\":{\"auth\":\"$(printf "%s:%s" "$NEXUS_USER" "$NEXUS_PASS" | base64 | tr -d '\n')\"}}}" >> /kaniko/.docker/config.json
    - echo "{\"proxies\":{\"default\":{\"httpProxy\":\"$HTTP_PROXY\",\"httpsProxy\":\"$HTTP_PROXY\",\"noProxy\":\"$NO_PROXY\"}}}"  >> /kaniko/.docker/config.json
    - export app_name=$(grep '"name"' $CI_PROJECT_DIR/web-app-vue/package.json | awk -F'"' '{print $4}')
    - export version=$(grep '"version"' $CI_PROJECT_DIR/web-app-vue/package.json | awk -F'"' '{print $4}')
  script:
    - >-
      /kaniko/executor \
        --context $CI_PROJECT_DIR/web-app-vue \
        --dockerfile $CI_PROJECT_DIR/web-app-vue/Dockerfile \
        --destination "$ANTIFRAUD_NEXUS_IMAGE_REPO/$app_name:$version" \
        --build-arg HTTP_PROXY=$HTTP_PROXY \
        --build-arg HTTPS_PROXY=$HTTP_PROXY || continue
    - echo "Image $app_name:$version pushed!"