version: '3.8'
services:

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - afs-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5417:${DB_PORT}"
    networks:
      - afs-network

  migrations:
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile_jar
      args:
        - JAR_FILE=./migrations/target/migrations*.jar
    environment:
      - DB_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - afs-network
    depends_on:
      - postgres


  ldap:
    build:
      context: ./config/ldap2
      dockerfile: Dockerfile
    ports:
      - 389:389
      - 636:636
    networks:
      - afs-network


  api-server:
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile_jar
      args:
        - JAR_FILE=./api-server/target/api-server*.jar
    environment:
      - API_SERVER_HOST=${API_SERVER_HOST}
      - API_SERVER_PORT=${API_SERVER_PORT}
      - LOG_PATTERN=${LOG_PATTERN}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_LEVEL_ROOT=${LOG_LEVEL_ROOT}
    ports:
      - "${API_SERVER_PORT}:${API_SERVER_PORT}"
    networks:
      - afs-network
    depends_on:
      - postgres
      - migrations

  api-gateway:
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile_jar
      args:
        - JAR_FILE=./api-gateway/target/api-gateway*.jar
    environment:
      - API_SERVER_HOST=${API_SERVER_HOST}
      - API_SERVER_PORT=${API_SERVER_PORT}
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}
      - LOG_PATTERN=${LOG_PATTERN}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_LEVEL_ROOT=${LOG_LEVEL_ROOT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - AUTH_LDAP_URL=${AUTH_LDAP_URL}
      - AUTH_LDAP_BASE=${AUTH_LDAP_BASE}
      - AUTH_LDAP_MANAGER_DN=${AUTH_LDAP_MANAGER_DN}
      - AUTH_LDAP_MANAGER_PASSWORD=${AUTH_LDAP_MANAGER_PASSWORD}
      - AUTH_LDAP_USER_SEARCH_BASE=${AUTH_LDAP_USER_SEARCH_BASE}
      - AUTH_LDAP_USER_SEARCH_FILTER=${AUTH_LDAP_USER_SEARCH_FILTER}
      - AUTH_LDAP_GROUP_SEARCH_BASE=${AUTH_LDAP_GROUP_SEARCH_BASE}
      - AUTH_LDAP_GROUP_SEARCH_FILTER=${AUTH_LDAP_GROUP_SEARCH_FILTER}
      - AUTH_JWT_SECRET=${AUTH_JWT_SECRET}
      - AUTH_JWT_LIFETIME=${AUTH_JWT_LIFETIME}


    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    networks:
      - afs-network
    depends_on:
      - postgres
      - migrations
      - api-server

  cpms:
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile_jar
      args:
        - JAR_FILE=cpms/target/cpms*.jar
    environment:
      - API_SERVER_HOST=${API_SERVER_HOST}
      - API_SERVER_PORT=${API_SERVER_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - QUEUE_CPMS_STEP_UPDATE=${QUEUE_CPMS_STEP_UPDATE}
      - QUEUE_CPMS_JOB_REQUEST=${QUEUE_CPMS_JOB_REQUEST}
      - QUEUE_DOWNLOADER_STEP_REQUEST=${QUEUE_DOWNLOADER_STEP_REQUEST}
      - QUEUE_IMPORTER_STEP_REQUEST=${QUEUE_IMPORTER_STEP_REQUEST}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - ZIPKIN_URL=${ZIPKIN_URL}
      - LOG_PATTERN=${LOG_PATTERN}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_LEVEL_ROOT=${LOG_LEVEL_ROOT}
    networks:
      - afs-network
    depends_on:
      - postgres
      - migrations
      - rabbitmq
      - api-server
      - api-gateway


  uploader:
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile_jar
      args:
        - JAR_FILE=uploader/target/uploader*.jar
    environment:
      - DOWNLOADER_MOUNT_POINT=/data
      - API_SERVER_HOST=${API_SERVER_HOST}
      - API_SERVER_PORT=${API_SERVER_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - QUEUE_CPMS_STEP_UPDATE=${QUEUE_CPMS_STEP_UPDATE}
      - QUEUE_CPMS_JOB_REQUEST=${QUEUE_CPMS_JOB_REQUEST}
      - QUEUE_DOWNLOADER_STEP_REQUEST=${QUEUE_DOWNLOADER_STEP_REQUEST}
      - QUEUE_IMPORTER_STEP_REQUEST=${QUEUE_IMPORTER_STEP_REQUEST}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - ZIPKIN_URL=${ZIPKIN_URL}
      - LOG_PATTERN=${LOG_PATTERN}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_LEVEL_ROOT=${LOG_LEVEL_ROOT}
    volumes:
      - ${DOWNLOADER_MOUNT_POINT}:/data
    networks:
      - afs-network
    depends_on:
      - postgres
      - migrations
      - rabbitmq
      - api-server
      - api-gateway


  enricher:
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile_jar
      args:
        - JAR_FILE=enricher/target/enricher*.jar
    environment:
      - API_SERVER_HOST=${API_SERVER_HOST}
      - API_SERVER_PORT=${API_SERVER_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - QUEUE_CPMS_STEP_UPDATE=${QUEUE_CPMS_STEP_UPDATE}
      - QUEUE_CPMS_JOB_REQUEST=${QUEUE_CPMS_JOB_REQUEST}
      - QUEUE_DOWNLOADER_STEP_REQUEST=${QUEUE_DOWNLOADER_STEP_REQUEST}
      - QUEUE_IMPORTER_STEP_REQUEST=${QUEUE_IMPORTER_STEP_REQUEST}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - ZIPKIN_URL=${ZIPKIN_URL}
      - LOG_PATTERN=${LOG_PATTERN}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_LEVEL_ROOT=${LOG_LEVEL_ROOT}
    networks:
      - afs-network
    depends_on:
      - postgres
      - migrations
      - rabbitmq
      - api-server
      - api-gateway

  scheduler:
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile_jar
      args:
        - JAR_FILE=scheduler/target/scheduler*.jar
    environment:
      - API_SERVER_HOST=${API_SERVER_HOST}
      - API_SERVER_PORT=${API_SERVER_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - QUEUE_CPMS_JOB_REQUEST=${QUEUE_CPMS_JOB_REQUEST}
      - ZIPKIN_URL=${ZIPKIN_URL}
      - LOG_PATTERN=${LOG_PATTERN}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_LEVEL_ROOT=${LOG_LEVEL_ROOT}
    networks:
      - afs-network
    depends_on:
      - postgres
      - migrations
      - rabbitmq
      - api-server
      - api-gateway

  downloader:
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile_jar
      args:
        - JAR_FILE=downloader/target/downloader*.jar
    environment:
      - API_SERVER_HOST=${API_SERVER_HOST}
      - API_SERVER_PORT=${API_SERVER_PORT}
      - DOWNLOADER_MOUNT_POINT=/data

      - QUEUE_CPMS_STEP_UPDATE=${QUEUE_CPMS_STEP_UPDATE}
      - QUEUE_CPMS_JOB_REQUEST=${QUEUE_CPMS_JOB_REQUEST}
      - QUEUE_DOWNLOADER_STEP_REQUEST=${QUEUE_DOWNLOADER_STEP_REQUEST}


      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - PROXY_HOST=${PROXY_HOST}
      - PROXY_PORT=${PROXY_PORT}
      - ZIPKIN_URL=${ZIPKIN_URL}
      - LOG_PATTERN=${LOG_PATTERN}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_LEVEL_ROOT=${LOG_LEVEL_ROOT}
    networks:
      - afs-network
    volumes:
      - ${DOWNLOADER_MOUNT_POINT}:/data
    depends_on:
      - postgres
      - migrations
      - rabbitmq
      - api-server
      - api-gateway

  importer:
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile_jar
      args:
        - JAR_FILE=importer/target/importer*.jar
    environment:
      - API_SERVER_HOST=${API_SERVER_HOST}
      - API_SERVER_PORT=${API_SERVER_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

      - QUEUE_CPMS_STEP_UPDATE=${QUEUE_CPMS_STEP_UPDATE}
      - QUEUE_IMPORTER_STEP_REQUEST=${QUEUE_IMPORTER_STEP_REQUEST}

      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - ZIPKIN_URL=${ZIPKIN_URL}
      - LOG_PATTERN=${LOG_PATTERN}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_LEVEL_ROOT=${LOG_LEVEL_ROOT}
    networks:
      - afs-network
    volumes:
      - ${DOWNLOADER_MOUNT_POINT}:/data
    depends_on:
      - postgres
      - migrations
      - rabbitmq
      - api-server
      - api-gateway

  web-frontend:
    build:
#      context: ./web-frontend
      context: ./web-app-vue
      dockerfile: Dockerfile_local
    environment:
      - VITE_API_PREFIX=${VITE_API_PREFIX}
      - API_GATEWAY_HOST=api-gateway
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}
    ports:
      - 80:80
    networks:
      - afs-network
    depends_on:
      - postgres
      - migrations
      - api-server
      - api-gateway





networks:
  afs-network:
    driver: bridge