<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>ua.com.valexa</groupId>
    <artifactId>afs</artifactId>
    <version>1.2.13</version>
    <name>afs</name>
    <description>afs</description>
    <packaging>pom</packaging>

    <modules>
        <module>afs-common</module>
        <module>migrations</module>
        <module>api-server</module>
        <module>api-gateway</module>
        <module>cpms</module>
        <module>scheduler</module>
        <module>downloader</module>
        <module>enricher</module>
        <module>importer</module>
        <module>sandbox</module>
        <module>uploader</module>
    </modules>

</project>
