spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: ${API_GATEWAY_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${API_SERVER_HOST}:${API_SERVER_PORT}/eureka




logging:
  pattern:
    console: ${LOG_PATTERN}
  level:
    ua.com.valexa: ${LOG_LEVEL}
    root: ${LOG_LEVEL_ROOT}

