spring.application.name=api-gateway

server.port=${API_GATEWAY_PORT}

eureka.client.service-url.defaultZone=${API_SERVER_HOST}:${API_SERVER_PORT}/eureka

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true


spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.driver-class-name=org.postgresql.Driver
spring.liquibase.default-schema=sys
spring.liquibase.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.liquibase.user=${DB_USER}
spring.liquibase.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}


logging.pattern.console=${LOG_PATTERN}
logging.level.ua.com.valexa=${LOG_LEVEL}
logging.level.root=${LOG_LEVEL_ROOT}

auth.ldap.url=${AUTH_LDAP_URL}
auth.ldap.base=${AUTH_LDAP_BASE}

auth.ldap.manager.dn=${AUTH_LDAP_MANAGER_DN}
auth.ldap.manager.password=${AUTH_LDAP_MANAGER_PASSWORD}

auth.ldap.user.search.base=${AUTH_LDAP_USER_SEARCH_BASE}
auth.ldap.user.search.filter=${AUTH_LDAP_USER_SEARCH_FILTER}

auth.ldap.group.search.base=${AUTH_LDAP_GROUP_SEARCH_BASE}
auth.ldap.group.search.filter=${AUTH_LDAP_GROUP_SEARCH_FILTER}

auth.jwt.secret=${AUTH_JWT_SECRET}
auth.jwt.lifetime=${AUTH_JWT_LIFETIME}