spring.application.name=sandbox
server.port=9999

eureka.client.service-url.defaultZone=http://${API_SERVER_HOST}:${API_SERVER_PORT}/eureka

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}



#spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
#spring.liquibase.driver-class-name=org.postgresql.Driver
#spring.liquibase.default-schema=scheduler
#spring.liquibase.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
#spring.liquibase.user=${DB_USER}
#spring.liquibase.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#queue.cpms.step.update=${QUEUE_CPMS_STEP_UPDATE}
#queue.cpms.job.request=${QUEUE_CPMS_JOB_REQUEST}
#queue.downloader.step.request=${QUEUE_DOWNLOADER_STEP_REQUEST}
#queue.importer.step.request=${QUEUE_IMPORTER_STEP_REQUEST}

#management.endpoint.health.show-details=always
#management.endpoints.web.exposure.include=health,info,prometheus
#management.health.db.enabled=true
#management.health.rabbit.enabled=true
#
#management.zipkin.tracing.endpoint=${ZIPKIN_URL}
#management.tracing.sampling.probability=1.0

logging.pattern.console=${LOG_PATTERN}
#logging.level.root=${LOG_LEVEL_ROOT}
logging.level.root=debug
logging.level.ua.com.valexa=${LOG_LEVEL}


#spring.ldap.embedded.ldif=classpath:test-server.ldif
#spring.ldap.embedded.base-dn=dc=springframework,dc=org
#spring.ldap.embedded.port=8389

#
#spring.ldap.urls=ldap://localhost:389/
#spring.ldap.base=dc=example,dc=com
#spring.ldap.username=cn=admin,dc=example,dc=com
#spring.ldap.password=admin
#spring.security.ldap.dn-pattern=uid={0},ou=users
#spring.security.ldap.search-base=ou=users
#spring.security.ldap.search-filter=(uid={0})


# LDAP server URL
#spring.ldap.urls=ldap://localhost:389/
#
## Base DN
#spring.ldap.base-dn=dc=example,dc=com
#
## Security principal and password for binding
#spring.ldap.username=cn=admin,dc=example,dc=com
#spring.ldap.password=3211
#
## User search base and filter
#spring.ldap.embedded.base-dn=dc=example,dc=com
#spring.security.ldap.user-dn-pattern=uid={0}
#
## Group search base and filter
#spring.security.ldap.authorities.group-search-base=ou=groups
#spring.security.ldap.authorities.group-search-filter=(uniqueMember={0})
#spring.security.ldap.authorities.group-role-attribute=cn




#
#
## LDAP server URL
#spring.ldap.urls=ldap://localhost:389
#spring.ldap.base=dc=raiffeisenbank,dc=com,dc=ua
#spring.ldap.username=cn=admin,dc=raiffeisenbank,dc=com,dc=ua
#spring.ldap.password=3211
#
## LDAP authentication
#spring.security.ldap.context-source.url=ldap://localhost:389
#spring.security.ldap.context-source.base=dc=raiffeisenbank,dc=com,dc=ua
#spring.security.ldap.context-source.user-dn=cn=admin,dc=raiffeisenbank,dc=com,dc=ua
#spring.security.ldap.context-source.password=3211
#
## LDAP user search
#spring.security.ldap.user-search-base=ou=Users
#spring.security.ldap.user-search-filter=(uid={0})
#
## LDAP group search
#spring.security.ldap.authorities.group-search-base=ou=Groups
##spring.security.ldap.authorities.group-search-filter=(uniqueMember={0})
#spring.security.ldap.authorities.group-role-attribute=cn
#
## Use memberOf attribute for group membership
#spring.security.ldap.authorities.group-search-filter=(memberOf=cn=afs_admin,ou=Groups,dc=example,dc=com)
# Enable debug logging for Spring Security LDAP
logging.level.org.springframework.security.ldap=DEBUG

# Enable debug logging for Spring LDAP core
logging.level.org.springframework.ldap=DEBUG


auth.ldap.url=${AUTH_LDAP_URL}
auth.ldap.base=${AUTH_LDAP_BASE}

auth.ldap.manager.dn=${AUTH_LDAP_MANAGER_DN}
auth.ldap.manager.password=${AUTH_LDAP_MANAGER_PASSWORD}

auth.ldap.user.search.base=${AUTH_LDAP_USER_SEARCH_BASE}
auth.ldap.user.search.filter=${AUTH_LDAP_USER_SEARCH_FILTER}

auth.ldap.group.search.base=${AUTH_LDAP_GROUP_SEARCH_BASE}
auth.ldap.group.search.filter=${AUTH_LDAP_GROUP_SEARCH_FILTER}

auth.ldap.rbac.map=${AUTH_LDAP_RBAC_MAP}



#spring.ldap.url=${AUTH_LDAP_URL}
#spring.ldap.base=${AUTH_LDAP_BASE}
#spring.ldap.username=${AUTH_LDAP_MANAGER_DN}
#spring.ldap.password=${AUTH_LDAP_MANAGER_PASSWORD}

#
#
#jwt.secret=your_secret_key
#jwt.expirationMs=86400000




#spring.security.ldap.authorities.group-search-filter=(member={0})
#spring.security.ldap.authorities.group-search-base=ou=groups

#spring.ldap.base: dc=raiffeisenbank,dc=com,dc=ua
#spring.ldap.username: cn=admin,dc=raiffeisenbank,dc=com,dc=ua
#spring.ldap.password: 3211
#spring.ldap.urls: ldap://localhost:389
#spring.security.ldap.userDnPatterns: sAMAccountName={0}
#spring.security.ldap.groupSearchBase: ou=Groups
#spring.security.ldap.groupSearchFilter: (uniqueMember={0})
#spring.security.ldap.authorities.groupSearchBase: ou=Groups
#spring.security.ldap.authorities.groupSearchFilter: (uniqueMember={0})
#spring.security.ldap.authorities.groupRoleAttribute: cn
#spring.security.ldap.authorities.convertToUpperCase: false