spring.application.name=scheduler
server.port=0

eureka.client.service-url.defaultZone=http://${API_SERVER_HOST}:${API_SERVER_PORT}/eureka

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.driver-class-name=org.postgresql.Driver
spring.liquibase.default-schema=scheduler
spring.liquibase.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.liquibase.user=${DB_USER}
spring.liquibase.password=${DB_PASSWORD}

#spring.jpa.hibernate.ddl-auto=update


queue.cpms.step.update=${QUEUE_CPMS_STEP_UPDATE}
queue.cpms.job.request=${QUEUE_CPMS_JOB_REQUEST}
queue.downloader.step.request=${QUEUE_DOWNLOADER_STEP_REQUEST}
queue.importer.step.request=${QUEUE_IMPORTER_STEP_REQUEST}

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,prometheus
management.health.db.enabled=true
management.health.rabbit.enabled=true

management.zipkin.tracing.endpoint=${ZIPKIN_URL}
management.tracing.sampling.probability=1.0

logging.pattern.console=${LOG_PATTERN}
logging.level.root=${LOG_LEVEL_ROOT}
logging.level.ua.com.valexa=${LOG_LEVEL}