spring.application.name=migrations

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.liquibase.default-schema=public

spring.liquibase.driver-class-name=org.postgresql.Driver

spring.liquibase.url=${DB_URL}
spring.liquibase.user=${DB_USER}
spring.liquibase.password=${DB_PASSWORD}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
