FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json ./

RUN yarn
COPY . .
RUN npm run build

ENV VITE_API_PREFIX=${VITE_API_PREFIX}
ENV API_GATEWAY_HOST=${API_GATEWAY_HOST}
ENV API_GATEWAY_PORT=${API_GATEWAY_PORT}

FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY ./config/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
EXPOSE 80
ENTRYPOINT ["/entrypoint.sh"]