spring.application.name=importer

server.port=0

eureka.client.service-url.defaultZone=http://${API_SERVER_HOST}:${API_SERVER_PORT}/eureka

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.driver-class-name=org.postgresql.Driver
spring.liquibase.default-schema=importer
spring.liquibase.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.liquibase.user=${DB_USER}
spring.liquibase.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

queue.cpms.step.update=${QUEUE_CPMS_STEP_UPDATE}    

queue.importer.step.request=${QUEUE_IMPORTER_STEP_REQUEST}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}



management.zipkin.tracing.endpoint=${ZIPKIN_URL}
management.tracing.sampling.probability=1.0

logging.pattern.console=${LOG_PATTERN}
logging.level.ua.com.valexa=${LOG_LEVEL}
logging.level.root=${LOG_LEVEL_ROOT}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.batch=DEBUG
logging.level.com.yourpackage=DEBUG