spring.application.name=downloader

server.port=0

eureka.client.service-url.defaultZone=http://${API_SERVER_HOST}:${API_SERVER_PORT}/eureka

downloader.mount.point=${DOWNLOADER_MOUNT_POINT}

queue.downloader.step.request=${QUEUE_DOWNLOADER_STEP_REQUEST}
queue.cpms.step.update=${QUEUE_CPMS_STEP_UPDATE}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}


proxy.host=${PROXY_HOST}
proxy.port=${PROXY_PORT}


management.zipkin.tracing.endpoint=${ZIPKIN_URL}
management.tracing.sampling.probability=1.0

logging.pattern.console=${LOG_PATTERN}
logging.level.root=${LOG_LEVEL_ROOT}
logging.level.ua.com.valexa=${LOG_LEVEL}