spring:
  application:
    name: api-server

server:
  port: ${API_SERVER_PORT}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${API_SERVER_HOST}:${API_SERVER_PORT}/eureka

logging:
  pattern:
    console: ${LOG_PATTERN}
  level:
    ua.com.valexa: ${LOG_LEVEL}
    root: ${LOG_LEVEL_ROOT}