spring.application.name=api-server

server.port=${API_SERVER_PORT}
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.client.service-url.defaultZone=http://${API_SERVER_HOST}:${API_SERVER_PORT}/eureka

logging.pattern.console=${LOG_PATTERN} 
logging.level.root=${LOG_LEVEL_ROOT}